// qm-user-token: xxl0ZRBJx9k2hlkvDu17Q9VTqsMIVqGJeWN1VFWdju2RkUM9ZW5NrAENqQ8PclmBgfd5svbDA3yF1mla1aDfMw
// cookie: acw_tc=ac11000117606860431305087e54579f36a9a30ac54c72640f127171449fbf;
// ssxmod_itna3=C50qzxnDRDcADtQ0=3DQGODhx+xmT50j663GRRDjg27T46bZPE642A40PPl6dqD//xAp=VDnKGnDQKDgDlKGgC44D15H/W8csDU4oDyDiIuxixDRYueihByD0wd5WRpNKUGqNwsPxA5DnDBdDK4Dv/xXtBE+sDG=mDBjVA+PC9kI9i2ps0l5=roA=9qAtZCutVeA+FpXFO=AseD;

function de() {
    return [
        "Thu3gKb",
        "2au85FuG2n",
        "2FUHukuS2FJ",
        "uyM/utB",
        "2a/z6PvC",
        "6tYxRu5",
        "gtyaP7Z",
        "YCYFT7j",
        "TFCwYdlauFJ",
        "E64Ti6LPi6ViEWdoi5QTi6DWi5SPi6LN",
        "2kuNTPuGTA",
        "uCMM2re",
        "2kN32tUMgFX",
        "gPMRgaK",
        "uduqUCb",
        "LrUu5bf",
        "Y7mG6Plw",
        "PdYIDkz",
        "Z+5NvRANvRZ",
        "PymLRk2",
        "m1mC27uC2aB",
        "Ztnhc+m9Zan",
        "Y7oC5n",
        "6PvoLPe",
        "UKTb5re",
        "UJm8gJe",
        "gbCwYklRDPX",
        "gCUSYPe",
        "2FvSYPuwuFJ",
        "2kC16tB",
        "R1TfUFK",
        "LKoUTyJ",
        "RPmmY1K",
        "2aUS6Pi16P5",
        "L1MURKX",
        "BkNkuJ9",
        "W=AaW=AhW=A",
        "TduGTA",
        "bPMGBFJ",
        "2aUS6Pi1",
        "eJvd7hyBby9",
        "c+/9",
        "R1m+T7f",
        "DKuPRdZ",
        "LdI4TP2",
        "vQnNZLnGsLn",
        "Y1M4DJ9",
        "Rr/bLblsbn",
        "vGeFvGArYkr75FCz",
        "TFyk7n",
        "ga/C21UMY7Z",
        "YJi7uu2",
        "5Fyzgdmo5Fz",
        "5Flw5Fyh",
        "PJIF6k9",
        "Y7vG5PTC",
        "5JrUBJh",
        "2PIPYFh",
        "6dlGTA",
        "ubraDu5",
        "gPlJYPn",
        "6Jlf2J2",
        "ThibDyK",
        "L7Y7uyb",
        "YPro6Pn",
        "TduXT=lfTdh",
        "5PmxT7BETdb",
        "5klhTdlI",
        "27uC21J",
        "57vC",
        "5Foo2JvxYdb",
        "ukvYL7f",
        "m1US5PvC6PB",
        "YrosTtZ",
        "bFiMUJh",
        "PdMZbP2",
        "mhr3T1vi",
        "TbIWTFB",
        "gKMSDKX",
        "67v/21moDB",
        "2tmxTdlhD7A",
        "bhUWukuS2FJ",
        "v=IQb8vksyZ",
        "2bM72Je",
        "RPmqud2",
        "5FynTdvf5bK",
        "ukrHguB",
        "LdoYb1e",
        "TC/YU1K",
        "5JmBP7K",
        "TdCxgJyzY7e",
        "UruFgr2",
        "YrTuP7B",
        "gam8YuYogdJ",
        "Z8JrZ+bnRyMsg7M6",
        "2tv8PPJ",
        "TdlRTtmMgk2",
        "v+BG",
        "YPi8gFUC7r9",
        "T1uqbkK",
        "LCubYdj",
        "gduJ",
        "2aUo21UGuFJ",
        "gt/wU1A",
        "2kukY7mc7n",
        "DKY1YuJ",
        "TbYt51J",
        "TdNJ",
        "uaTkTC5",
        "udT/BC5",
        "P1mtU7B",
        "LKMaudf",
        "udifBFf",
        "2FuhWPvxgFz",
        "YJlhPbb",
        "ThTLUhb",
        "TKi7b1J",
        "27uCDJK",
        "5Pva7aU8",
        "ga/C21Ui",
        "ga/h6Plw2n",
        "Y8Co5RBFZkK",
        "LkN8gJe",
        "PkNZUdZ",
        "6PuwTdyh6P9",
        "2FoMY1B",
        "WdhM",
        "2dlSTA",
        "TdioZn",
        "gJr8RPb",
        "RbrhuKB",
        "YduF6PvCRae",
        "RFveurJ",
        "2bytPtA",
        "LPBEetmC27b",
        "bFi/baf",
        "gaMIutb",
        "R7/e2yA",
        "RC/6guA",
        "YtU1YCj",
        "TuvL6Kj",
        "ubisRbz",
        "byub",
        "gPuIgamibFJ",
        "utCnYB",
        "YtCegavhu7e",
        "TPiG6dCkTA",
        "6dlGTdiogPb",
        "5PNz",
        "Ytu+6uK1WA",
        "LaozTtB",
        "BhMkbPj",
        "LyT+LJ9",
        "ghIRude",
        "Z=XSW8KG",
        "WKfM",
        "eduS2klS",
        "6yvR5a5",
        "2aUoTtuGBkK",
        "5u/nbhn",
        "6dKxBuToYJZ",
        "27UHgKe",
        "b7mL6k5",
        "5ko16d2",
        "TuvY6k5",
        "BhoMRy2",
        "2t/c2FUH7a5",
        "YkCS2aB",
        "Pduku7b",
        "UKTMZyC/vhe",
        "2hy6Ty2",
        "DPm/buA",
        "5rTYUKK",
        "5PvhukJ",
        "2aU1bPJ",
        "LboqBJX",
        "6Q9i57yCvPn",
        "m1TMgkUxTrb",
        "gkNyLJJ",
        "RJvQuuJ",
        "TFyk7FCG7Fh",
        "5ums2y2",
        "RbvZPkJ",
        "DPCvbhz",
        "gaCYYKB",
        "6auiLbb",
        "ghueTtf",
        "TdCIY7vh5Ph",
        "ZR5ze+Kze+Z",
        "LhCds7UuDQ9",
        "UJILghe",
        "T7UxbaUx2K9",
        "TtvhgF9",
        "UFN62yK",
        "uhYHDkh",
        "PPUzLK5",
        "5kNrY7UxgaB",
        "uFNQ6P5",
        "uPTyYPZ",
        "YC/bU7Z",
        "sRAnv8BnUJrsRJmn",
        "u1/B6tf",
        "LPlNUPK",
        "PyMG572",
        "L1CtYFJ",
        "YtUf",
        "6umY6hj",
        "Z8enZR5nZ+/bTkC35F2",
        "gbyQbdj",
        "2auQ2aUS6PX",
        "u1mLu7B",
        "5ayfR1Z",
        "Tamo6PX",
        "6bCPLKf",
        "YPvh",
        "TFCJTdj",
        "Dko=YPz",
        "bdy1YblnTdJ",
        "2kungdy8YB",
        "Uhub",
        "BayqDt5",
        "5Foo2Jyh",
        "Y7mSgae",
        "Y7vhLPikgSX",
        "gCvfga2",
        "Uuu8btJ",
        "6koWDbZ",
        "PtoRThf",
        "TJUbUJh",
        "YkZrZFuQvke",
        "YJoBYa5",
        "6hM=uh5",
        "2bMQTPf",
        "bhYY67Z",
        "bdmfLF2",
        "6hrPTt5",
        "YKvtRCe",
        "buC+YkX",
        "W=AGvSnjZRe",
        "6duoYduS2n",
        "RyoZB15",
        "gFiG",
        "gPC82kln6d9",
        "RuvNghn",
        "Y8ZGYkKF5Fb",
        "uuvfYkz",
        "6dlS67MCYA",
        "Lbo1Rk5",
        "DdoSZklyRF2",
        "RryZPJj",
        "6PiJY7o3Yj",
        "Z8eze+eGW=A",
        "5uCPB1j",
        "27TbTPUZ6hh",
        "6dyGRaTwbte",
        "bhIxLr5",
        "bkoWR7e",
        "UkNt2d2",
        "2au=5bz",
        "gPBr7r9",
        "gduwYaUf",
        "ZQXiW8b",
        "W=ASs=njZGB",
        "gPyh5Fj",
        "YaoQ2dK",
        "YuTqDPz",
        "YbCwYk9",
        "2PI4bKh",
        "TCT/LFJ",
        "PJCXurJ",
        "TyMh6k5",
        "YbyrTdox2kJ",
        "WGU1sdjFvFB",
        "YPi8gFUC",
        "YFuhudCIYB",
        "5FIb2ae",
        "2kuFY7mGYB",
        "PJoK5aK",
        "5uYvbab",
        "51uMgdU3gkn",
        "TGKxZPCwDR2",
        "5FyzgA",
        "5PmM",
        "5PN35kMC5aB",
        "TdCIYulc",
        "585GYR2hvkB",
        "D1mIBFB",
        "UhrNuhj",
        "5FlI2dNCTdb",
        "bKlRuA",
        "RC/wPPe",
        "EWDGEWFzE6qZE4V/iE=/TkCC",
        "Ukv4grb",
        "5Flw2FlzYB",
        "2dyh6A",
        "TkySedySYGK",
        "YkCXPCZ",
        "gklwYB",
        "gkCQuhK",
        "BJmx5uf",
        "UKifRyf",
        "PKvoRhh",
        "UKuZUuUy",
        "6dyG6A",
        "61m+uhB",
        "YdlI5PCw",
        "5kCwYyUf67Z",
        "uavk2JK",
        "2tuG6A",
        "bPv1gh9",
        "gPuh6dlJ",
        "TduXTA",
        "gPyX",
        "7aToYClaYPK",
        "2du/PdK",
        "bPI52b9",
        "bKihub2",
        "brMngdZ",
        "TdCxgJyrTdj",
        "gCUfRPj",
        "ey9nD+ervG5",
        "Wa/oYFuGWhK",
        "2dla",
        "TdCxgJmoYd2",
        "BPbXR+2nRk9",
        "TdMvguB",
        "2FuhUdyh5B",
        "bdTwDdJ",
        "T7vC2CuGY7e",
        "Pdi5bhz",
        "ZGAnZG5iZ+A",
        "57vG6PTw",
        "Y7TEPdJ",
        "PJMm2Ff",
        "2Fuo2kvf",
        "B7YC21b",
        "Trm+ubn",
        "LJrSB7J",
        "2dT72CA",
        "2PrqYaj",
        "ZanNc+m9vtn",
        "TkCK5JJ",
        "gFyJ",
        "Lbvo2u5",
        "LdN8UKn",
        "2dyS2Fb",
        "gPuSbdB",
        "6klMgj",
        "ThIFB1b",
        "BkvdbKf",
        "YrME5Pe",
        "gkyF6PToTdb",
        "bJrB57B",
        "6bC+Pue",
        "B7vzYtK",
        "YPio5kNCUdb",
        "bFuhTdCwYn",
        "PdyoUr2",
        "bJoxuhj",
        "5FlIgrb",
        "TPiJYPYMgkb",
        "Lbmm5Pf",
        "Y1/SP7b",
        "Y1UMBu2",
        "TFN6RFz",
        "uFIMUtb",
        "2KTr5Jh",
        "gdyGTKCwYdb",
        "P1U3grJ",
        "PdIU215",
        "ubmPRaZ",
        "Z82XZ+AGvGb",
        "ZG2nsRjFsde",
        "uKok6P5",
        "UJiXuaf",
        "g7/Juaf",
        "b1y8L1A",
        "RuCU2h9",
        "5PNMD7uw7n",
        "RKr7YJh",
        "UaY/bFe",
        "DdokLdh",
        "2JvPgKj",
        "6tUh2A",
        "67/867Ui7r9",
        "5FUSRkZ",
        "TFCwYdlaLdb",
        "RKIYbt5",
        "DkiiTk9",
        "YkyMgA",
        "5uYUgCK",
        "5FynTdvf5uA",
        "bFNXguZ",
        "5kIn5bK",
        "PyUbgt2",
        "UPio5kNCYA",
        "YPio5kNCBF9",
        "BbTUDdf",
        "6hNCTkuz",
        "TkuS2FCxgj",
        "YamMYrJ",
        "e+KXW+enW=A",
        "6hrv5hf",
        "RkvtTtJ",
        "2FuhBFlrg1B",
        "P7Yeuuj",
        "61vxgClx2C9",
        "Z8bze+KGW=A",
        "58bG",
        "UJm8bye",
        "U1YSbCe",
        "TKCSB1J",
        "TkyS",
        "YtCqRPn",
        "YtCkUuZ",
        "5rm3RFe",
        "Rklx5h5",
        "brUwBh9",
        "uC/NUbYsvbf",
        "ZtnNc+m9vtn",
        "2JoC6PTfTA",
        "YKvBYJe",
        "Lyvzurj",
        "u7/nY7m+57Z",
        "BavnRkh",
        "YkCzYPiogPb",
        "TJUJTaZ",
        "gkuCYKUi",
        "Uty66be",
        "L7y75Pz",
        "YFuhbaCGTdb",
        "T7M/uKZ",
        "6KviBFB",
        "YyYyDPz",
        "Ydyh5B",
        "gamMDkuJ",
        "gKiHYbb",
        "PJMaDb5",
        "PGKrW+ZrW+e",
        "2PyaBh9",
        "gFmqYPvh",
        "m1Ui2dbl",
        "DuoP2yA",
        "7rln2klhgr9",
        "TkiZgdf",
        "2Fm=LrK",
        "byoHDJf",
        "2FykYbySYPK",
        "TFiuDkZ",
        "67/auFj",
        "2KvqL1Z",
        "Pbv=5Jz",
        "Y1uw5aUMgFX",
        "WSBN",
        "2FuSLPikgGh",
        "D+vMYFrJ2J5",
        "urUIubJ",
        "57/n6FuisQA",
        "DkuJ",
        "2tmxTdl8gFn",
        "RkN1B72",
        "5Ruksde",
        "6Jm4YKh",
        "2uU5bdh",
        "2aMQTyY8TPj",
        "TKyrTdox2kJ",
        "uKIbbbh",
        "ZRmPB7TxU7b",
        "gFmMgdb",
        "6PyrgPX",
        "TPMJTdf",
        "61m/2K5",
        "PkmS6hz",
        "vhrZg7TFvJK",
        "YduF6PvCBPe",
        "6uJN6kTSLyf",
        "UPYdDt2",
        "Tdln",
        "5CTs2Pz",
        "etef5B",
        "UamMbbe",
        "51mogkB",
        "bhySTFX",
        "2bIoPke",
        "vRZrZGbrst/PDbUfbn",
        "6PiJY7j",
        "DCyxTJn",
        "gFiR6dla",
        "ZLnjZGeze+e",
        "gku/T7Ufgae",
        "U1Tk6hh",
        "DkTL6Jf",
        "Tdox2kCEYPB",
        "ghCqb7J",
        "Rhizgyj",
        "U7ohDbK",
        "UtuJUCZ",
        "TdySYFuhRFe",
        "TCuERhB",
        "TdCxgCvxTPX",
        "DtoyTJ9",
        "2Fow2bJ",
        "E4Vai5wOE5Dvi6Lvi5QTi6DWi5SP",
        "LKyy2tA",
        "W=ANsLnGZLn",
        "YymC2dZ",
        "TFCk6buw5Pe",
        "LCvNDtf",
        "uFykBFynTdZ",
        "urT1uJf",
        "5ry/6kh",
        "5FyIY7moB7b",
        "gdl857UMgFX",
        "ZG2N5PZrZPK",
        "TdlZgaTC2JZ",
        "RhmPYyf",
        "2dCXYPNL57B",
        "bdoaLkJ",
        "TkIR2J2",
        "Yduh5PCz",
        "gCvz2Je",
        "LbMb6Jh",
        "v+Aze+eaW=A",
        "5Pva7av87r9",
        "5FynTdvf5b5",
        "YKyrTdox2kJ",
        "bt/o5GhFZuf",
        "TkySeKy+7h9",
        "DJliTue",
        "vQnjZQnjZGA",
        "RhNdTFn",
        "6PXw27Kw5F9",
        "W=AGvCh",
        "urv/YtA",
        "v7YeDbi52r5",
        "uKo7gPe",
        "6duMYFoh",
        "6PTfTA",
        "bkCQUyJ",
        "bC/UP7b",
        "5PUJ67UMgFX",
        "TkChPbz",
        "TdlZgFvogdb",
        "3auSg+h",
        "2FNM5Fb",
        "YFuhBFlrg1B",
        "B1TRvbT+",
        "BhI=Ud5",
        "u7vdb1j",
        "s=njZRBze+e",
        "6Kuw5PmzYPB",
        "UhCN6Ce",
        "gFie6PUC",
        "6ku8TA",
        "2KyC6Ph",
        "5JCW2PZ",
        "DKTfgtM7ZFK",
        "5PTCu7mz",
        "gKNM2aB",
        "5PNQTPr/T7B",
        "YhMU2re",
        "5PChUkCw67Z",
        "LuuG2JZ",
        "2yYsba2",
        "BFlwTduwT=h",
        "gau=PtJ",
        "LPU5bue",
        "5FIbTA",
        "27/n6d5",
        "RdU/Td2",
        "vGmCsP5",
        "YPiJ57m/T7B",
        "PtmS2P9",
        "RPNI6tZ",
        "2doxgku+5Pn",
        "g1YILKK",
        "6tUh2tZE",
        "5FynTdvf5u2",
        "gdud5hj",
        "T7mz",
        "LPikgGh",
        "6tYJLkj",
        "PKyiDyK",
        "51u1",
        "gFMrB7Z",
        "5Jregye",
        "g1/HUhZ",
        "57/h5Foo",
        "PuY+Lyb",
        "2aTLRF9",
        "TdIHY1f",
        "gKTHUdX",
        "6Jom6aJ",
        "gaYJUbh",
        "RtvZBaA",
        "L7uwBCmQY1A",
        "Dym8BF5",
        "6FMZT15",
        "TFTI6dJ",
        "BblCut5",
        "LCM6DPB",
        "2kywYdlI",
        "i5PfigdAi5QTi6DWi5SPi6LNEWLC",
        "6kTtDdK",
        "5kukgamC",
        "YdULTbf",
        "5a/rutCnYB",
        "bhN8LrZ",
        "sLnSv=nGZSn",
        "YKMfgrA",
        "LPTQ57K",
        "DCCyYFj",
        "TFmM275",
        "gdywYauoYFb",
        "gFIMYB",
        "61vxgj",
        "5aoKRtJ",
        "TFuQukCCTrZ",
        "6PySBk5",
        "57/MW1TC67j",
        "esPECsDbqs6joVQxoj",
        "5kuw5FoI57e",
        "B7uh6dlS67f",
        "L7TIDJJ",
        "L1mtbaj",
        "Rtof61A",
        "2krk6PX",
        "5klxgduogj",
        "RFN+gr5",
        "Y7mSgaeE",
        "BhT82he",
        "ZGAnZ+Kav8A",
        "TbrkYdf",
        "TdNJ3n",
        "ZFBn",
        "grTsbJ5",
        "uKCXBPn",
        "uty3TK9",
        "gbNabkh",
        "YkNxgae",
        "2tBj3L/p",
        "2FvSYPuwLdb",
        "2aCGTduI",
        "6yvRgJb",
        "YklwTyvMDkb",
        "bKCf6Fe",
        "gklh6PYM5FK",
        "D7UrDub",
        "ZFy1",
        "2ylc",
        "5umX67J",
        "TtmMYFuSutJ",
        "LyCoRuB",
        "5kCwYA",
        "6Jr8P1A",
        "YPr7gCyqBFn",
        "YuCbUFn",
        "PPitukf",
        "bdNk5rB",
        "5FlwTduwT=h",
        "BFUz51B",
        "b7ymDbX",
        "T1mm2bz",
        "bKiU2kB",
        "2dowbFj",
        "51uMgdU3gJh",
        "gtT6B7B",
        "ZGZFvReSZduiL1yrbA",
        "LtMnLhj",
        "gdUzgke",
        "uhmHRdX",
        "5PYhY7e",
        "v+eav8ZNv7MB5kUGPB",
        "6am3Tt5",
        "6KYzDkf",
        "TKTM6Fz",
        "gumfLaf",
        "5CmKUbf",
        "RPIU6bb",
        "YkCzYB",
        "6Fui2n",
        "b1UoDCA",
        "2CT5UyZ",
        "vkniTC/42+K",
        "Dtm+ube",
        "2aUoTtuGBF9",
        "DyTLPkz",
        "uPM+bKh",
        "LPNuP7B",
        "Z+AXvR5nZ+5",
        "ZR2ze+bze+Z",
        "YKIaUbe",
        "6aM7bbf",
        "67MCYA",
        "5aurbr2",
        "TkyzTPb",
        "Yduk6PiCbte",
        "TdoCgPb",
        "6KlxD12",
        "PbNRT1Z",
        "gkuCYKvxgdn",
        "PJiJbPZ",
        "6tUh2tZEWS9",
        "WShN",
        "2avXgPlJ7FJ",
        "6hyG6JK",
        "T7mzYPi8gFB",
        "bFuhWbvxgFz",
        "YkCou7A",
        "2Pmv2yJ",
        "Dy/iRdj",
        "UtYEYdn",
        "Z1nr",
        "uhydeQnjWS9",
        "UumZUCZ",
        "TtCuUtf",
        "U7CPYy2",
        "6C/FP7Z",
        "2auQ",
        "5FynTdvf5ub",
        "6tUh2tZ",
        "uCYhTKB",
        "PkvCBCB",
        "Zanhc+y9Ztn",
        "Ydu8gFUC7r9",
        "TtCnYB",
        "TdYkRPj",
        "TFCwYdlaWC9",
        "YFuhUduF6PZ",
        "TtCnYulc",
        "5Flx6FCC",
        "gCuIDtK",
        "gPyMgtUx",
        "2uTwP7K",
        "5CYdBu2",
        "DuMCb7f",
        "6duoYduS",
        "2a/z67B",
        "Zanhc+m9Ztn",
        "Urm5LJ5",
        "s=njZRAze+J",
        "LdYX6dB",
        "TVPJzDQhMB",
        "bbUfTaA",
        "gdukTA",
        "RJU75F5",
        "2dNoTdYx2kh",
        "P7MJBF2",
        "edbfgA"
    ]
}
// 定义变量 t，避免出现 undefined 错误
var t = {};
t.register16023Reporter = async()=>{
                    r.default.info("[Reporter_16023]", "register16023Reporter start.");
                    const e = await a.default.getCurrentPerfInfo();
                    let t = 0;
                    setInterval((async()=>{
                        (0,
                        s.reportKeyValue)(await (async()=>{
                            const n = Date.now()
                              , i = await a.default.getCurrentPerfInfo()
                              , r = Math.ceil((n - o.publicreporterInfo.launchStartTs) / 1e3)
                              , s = "function" == typeof window.getStatsData ? window.getStatsData() : {
                                fps: 0,
                                jank: 0,
                                bigJank: 0,
                                jankTime: 0,
                                renderTime: 1
                            };
                            return t = Math.max(window.fps, t),
                            {
                                key: 16023,
                                value: [o.publicreporterInfo.sessionId, o.publicreporterInfo.appId, o.publicreporterInfo.appVersion, o.publicreporterInfo.appState, o.publicreporterInfo.appType, 0, o.publicreporterInfo.scene, 0, 0, s.fps, 0, 0, i.memory, i.memory - e.memory, 0, 0, r, 0, c(o.publicreporterInfo.canvasType), 0, 0, 0, 0, 0, t, 0, 0, 0, 0, 0, 0, 0, s.jank, s.bigJank, s.jankTime / s.renderTime * 1e4, 0, 0, 1, "3.3.5", 0].join(",")
                            }
                        }
                        )())
                    }
                    ), 6e4)
                }

const ge = {},
me = /acw_tc=([0-9a-f]+)(;|$)/;
function ye(t, e) {
	var n = 299,
	o = 242,
	i = 283,
	a = 535,
	s = 242,
	c = 203,
	u = 441,
	l = r,
	d = {};
	d[l(535)] = l(n),
	d[l(o)] = function(t, e) {
		return t < e
	};
	var p = d;
	tl(i) + "th" && p[l(s)](1, (t = mel(c))[l(u)]) && (ge[e] = t[1])
}
function _e(t, e) {
	var n = 294,
	o = 917,
	i = 313,
	a = 373,
	s = 838,
	c = 610,
	u = r,
	l = {
		OcHWY: u(888) + "ie",
		tstoo: u(n) + "ie",
		YnGVj: function(t, e) {
			return t(e)
		},
		IqWak: function(t, e, n) {
			return t(e, n)
		}
	};
	if (t = t[u(o)] ? t[u(o)][l[u(i)]] || t[u(o)][l[u(a)]] : "") for (var d of l[u(s)](b, t)) l[u(c)](ye, d, e),
	l[u(c)](zt, d, e)
}
function ve(t) {
	var e = 779,
	n = 663,
	o = 745,
	i = 325,
	a = 406,
	s = 840,
	c = 906,
	u = 533,
	l = 882,
	d = 246,
	p = 866,
	f = 917,
	h = 663,
	g = 406,
	m = 431,
	y = r,
	_ = {};
	_[y(e)] = function(t, e) {
		return t == e
	},
	_[y(n)] = y(o) + y(i),
	_[y(a)] = y(s) + y(c),
	_[y(u)] = function(t, e) {
		return t < e
	},
	_[y(l)] = y(d) + "l";
	var v = _;
	return v[y(e)](200, t[y(p) + "de"]) && (t = t[y(f)][v[y(h)]] || t[y(f)][v[y(g)]]) && v[y(u)]( - 1, ty(m))
}
function ke1(t) {
	var n = de();
    e = undefined;
	return ke = function(e, r) {
		var o = n[e -= 181];
		if (void 0 === ke.HKwASI) {
			ke.VVfjcW = function(t) {
				// 添加检查确保 t 不是 undefined
				if (typeof t !== 'string') {
					return '';
				}
				for (var e, n, r = "",
				o = "",
				i = 0,
				a = 0; n = t.charAt(a++);~n && (e = i % 4 ? 64 * e + n: n, i++%4) ? r += String.fromCharCode(255 & e >> ( - 2 * i & 6)) : 0) n = ("zIwxnNSGhrFaXiEp9lVOA/=+Kydtem4WZvs3BULRbuP75Y6g2TDcjoQ8JCk1fMqH0".indexOf(n) - 20 + 64) % 64;
				for (var s = 0,
				c = r.length; s < c; s++) o += "%" + ("00" + r.charCodeAt(s).toString(16)).slice( - 2);
				return decodeURIComponent(o)
			},
			t = arguments,
			ke.HKwASI = !0
		}
		var i = e + n[0],
		a = t[i];
		return a ? o = a: (o = ke.VVfjcW(o), t[i] = o),
		o
	};
	// 修复无限递归问题，调用 ke 而不是 ke1
	return ke(t, e);
}
function be(t, e) {
	var n = 299,
	o = 311,
	i = 704,
	a = 749,
	s = 704,
	c = 551,
	u = 311,
	l = 749,
	d = r,
	p = {};
	p[d(551)] = d(n),
	p[d(o)] = d(i) + "v2",
	p[d(a)] = d(s) + "v3";
	var f = p;
	for (var g of[[f[d(c)], ge], [f[d(u)], h], [f[d(l)], Ft]]) g[1][e] && (t[g[0]] = g[1][e])
}
function ke(t, e) {
	var n = de();
	return ke = function(e, r) {
		var o = n[e -= 181];
		if (void 0 === ke.HKwASI) {
			ke.VVfjcW = function(t) {
				// 添加检查确保 t 不是 undefined
				if (typeof t !== 'string') {
					return '';
				}
				for (var e, n, r = "",
				o = "",
				i = 0,
				a = 0; n = t.charAt(a++);~n && (e = i % 4 ? 64 * e + n: n, i++%4) ? r += String.fromCharCode(255 & e >> ( - 2 * i & 6)) : 0) n = ("zIwxnNSGhrFaXiEp9lVOA/=+Kydtem4WZvs3BULRbuP75Y6g2TDcjoQ8JCk1fMqH0".indexOf(n) - 20 + 64) % 64;
				for (var s = 0,
				c = r.length; s < c; s++) o += "%" + ("00" + r.charCodeAt(s).toString(16)).slice( - 2);
				return decodeURIComponent(o)
			},
			t = arguments,
			ke.HKwASI = !0
		}
		var i = e + n[0],
		a = t[i];
		return a ? o = a: (o = ke.VVfjcW(o), t[i] = o),
		o
	},
	ke(t, e)
}
var Ce = {
	wx: function() {
        var t = 655,
            e = 802,
            n = 579,
            o = 662,
            i = 241,
            a = 823,
            s = 927,
            c = 787,
            l = 324,
            d = 262,
            p = 536,
            f = 764,
            h = 794,
            g = 580,
            m = 878,
            y = 697,
            _ = 209,
            v = 386,
            b = 822,
            k = 718,
            C = 189,
            T = 567,
            S = 718,
            w = 339,
            I = 601,
            x = 825,
            P = 537,
            O = 312,
            A = 305,
            D = 925,
            L = 210,
            E = 658,
            N = 248,
            M = 396,
            R = 717,
            j = 377,
            B = 731,
            U = 693,
            G = 576,
            F = 687,
            q = 282,
            V = 740,
            H = 427,
            z = 692,
            W = 673,
            $ = 803,
            K = 423,
            J = 670,
            Y = 874,
            Q = 827,
            Z = 499,
            X = 616,
            tt = 271,
            et = 646,
            nt = 639,
            rt = 504,
            ot = 452,
            it = 639,
            at = 827,
            st = 680,
            ct = 706,
            ut = 755,
            lt = 752,
            dt = 427,
            pt = 810,
            ft = 489,
            ht = 741,
            gt = 909,
            mt = 447,
            yt = 698,
            t = 208,
            vt = 194,
            bt = 766,
            kt = 555,
            Ct = 495,
            Tt = 293,
            St = 793,
            wt = 488,
            It = 489,
            xt = 611,
            Pt = 207,
            Ot = 489,
            At = 747,
            Dt = 296,
            Lt = 196,
            Et = 333,
            Nt = 591,
            Mt = 380,
            Rt = 489,
            jt = 741,
            Bt = 303,
            Ut = 413,
            Gt = 363,
            Ft = 915,
            qt = 735,
            Vt = 896,
            Ht = 842,
            zt = 412,
            Wt = 489,
            $t = 628,
            Kt = 609,
            Jt = 482,
            Yt = 292,
            Qt = 845,
            Zt = 736,
            Xt = 539,
            te = 873,
            ee = 426,
            ne = 287,
            re = 574,
            oe = 389,
            ie = 916,
            ae = 518,
            se = 225,
            ce = 416,
            ue = 378,
            le = 652,
            de = 562,
            pe = 489,
            fe = 837,
            he = 264,
            ge = r,
            me = {
                gJQsR: function (t, e, n) {
                    return t(e, n)
                },
                PhwJi: ge(463),
                nTreb: ge(t) + "i",
                mjSoq: ge(e) + ge(n),
                bMHlR: ge(o),
                FNxWz: ge(i),
                peAXa: ge(a),
                TnhCj: ge(s),
                wbiqv: ge(c),
                WsfrA: ge(l) + "ze",
                IdXQR: function (t, e, n) {
                    return t(e, n)
                },
                wGRGE: ge(d) + "on",
                KTUaJ: ge(p) + ge(f),
                HWCJO: ge(h),
                FvrRR: ge(g),
                fPTEs: ge(m),
                JlcnB: ge(y) + "io",
                qJbuj: ge() + ge(v),
                MCLZi: ge(b) + ge(k),
                bVFAW: ge(C) + ge(v),
                pAeim: ge(T) + ge(S),
                tyUDz: ge(w) + ge(I),
                QqIyN: ge(x) + ge(P),
                kJBWF: ge(O) + ge(A) + "n",
                DqZiB: ge(D),
                XCaOM: ge(L),
                HJwTj: ge(E),
                phnSh: ge(N),
                bIKqc: ge(M),
                RHoWH: ge(R),
                kzWQJ: ge(j) + ge(B),
                UShfk: ge(U) + ge(G),
                uFGby: ge(F) + ge(q),
                bkpaA: ge(V) + ge(H),
                mAbPh: ge(z) + ge(W),
                yZeQz: ge(U) + ge($) + "ed",
                JMrAy: ge(K) + ge(J) + ge(Y),
                HkJug: ge(Q) + ge(Z) + ge(X),
                kMVtv: ge(Q) + ge(tt) + ge(et) + ge(nt),
                Wlbif: ge(Q) + ge(rt) + ge(ot) + ge(it),
                jrApF: ge(at) + ge(st) + ge(ct) + ge(it),
                xhfHm: ge(ut) + ge(lt) + ge(dt),
                eYTGl: function (t, e) {
                    return t + e
                },
                qJWrB: ge(pt)
            },
            ye = [];
            ye[ge(ft)](me[ge(ht)](u, wxge(gt) + ge(mt), [me[ge(yt)], me[ge(_t)], me[ge(vt)], me[ge(bt)], me[ge(kt)], me[ge(Ct)], me[ge(Tt)], me[ge(St)], me[ge(wt)]]))
    }
}
function f(t, e) {
                        for (var n = zt, r = Wt[n(l)][n(d)]("|"), o = 0; ; ) {
                            switch (r[o++]) {
                            case "0":
                                var i, a = {};
                                continue;
                            case "1":
                                if (Wt[n(p)](Wt[n(f)], t))
                                    return Wt[n(h)]($t);
                                continue;
                            case "2":
                                if (!t)
                                    return e;
                                continue;
                            case "3":
                                return Wt[n(g)](t, a) ? a[t] : Wt[n(m)]("{}", t) ? a : void 0;
                            case "4":
                                if (t = t[n(y)](),
                                i = e[n(_)](/^mailto:([^\/].+)/))
                                    a[n(v)] = Wt[n(b)],
                                    a[n(k)] = i[1];
                                else
                                    for (var s = Wt[n(C)][n(T)]("|"), c = 0; ; ) {
                                        switch (s[c++]) {
                                        case "0":
                                            if ((i = (e = (i = e[n(S)](/(.*?)\/#\!(.*)/)) ? Wt[n(w)](i[1], i[2]) : e)[n(_)](/(.*?)#(.*)/)) && (a[n(I)] = i[2],
                                            e = i[1]),
                                            a[n(x)] && t[n(P)](/^#/))
                                                return Wt[n(O)](Jt, t, a[n(I)]);
                                            continue;
                                        case "1":
                                            Wt[n(A)]($t) && (i = a[n(D)][n(_)](Wt[n(L)]($t))) && (a[n(E)] = i[3],
                                            a[n(N)] = i[2] ? Wt[n(w)](Wt[n(w)](i[2], "."), i[3]) : void 0,
                                            a[n(M)] = i[1] || void 0),
                                            a[n(R)] = Wt[n(j)](a[n(D)], a[n(B)] ? Wt[n(U)](":", a[n(G)]) : ""),
                                            a[n(F)] = a[n(q)] || (Wt[n(p)](Wt[n(V)], a[n(v)]) ? Wt[n(H)] : "80"),
                                            a[n(z)] = a[n(z)] || (Wt[n(W)](Wt[n($)], a[n(B)]) ? Wt[n(K)] : Wt[n(J)]);
                                            continue;
                                        case "2":
                                            if ((i = e[n(Y)](/(.*?)\:?\/\/(.*)/)) && (a[n(z)] = Wt[n(U)](i[1][n(Q) + n(Z)](), ":"),
                                            e = i[2]),
                                            (i = e[n(X)](/(.*?)(\/.*)/)) && (a[n(tt)] = i[2],
                                            e = i[1]),
                                            a[n(tt)] = (a[n(et)] || "")[n(nt)](/^([^\/])/, Wt[n(rt)]),
                                            (t = t[n(ot)](/^[\-0-9]+$/) ? t[n(nt)](/^([^\/])/, Wt[n(it)]) : t)[n(X)](/^\//))
                                                return Wt[n(at)](Kt, t, a[n(tt)][n(st) + "g"](1));
                                            continue;
                                        case "3":
                                            if ((i = (i = Wt[n(at)](Kt, Wt[n(ct)], a[n(tt)][n(st) + "g"](1))) && i[n(_)](/(.*?)\.([^.]+)$/)) && (a[n(ut)] = i[0],
                                            a[n(lt)] = i[1],
                                            a.n = i[2]),
                                            (i = e[n(P)](/(.*)\:([0-9]+)$/)) && (a[n(G)] = i[2],
                                            e = i[1]),
                                            (i = e[n(dt)](/(.*?)@(.*)/)) && (a.G = i[1],
                                            e = i[2]),
                                            a.G && (i = a.G[n(_)](/(.*)\:(.*)/),
                                            a.b = i ? i[1] : a.G,
                                            a.m = i ? i[2] : void 0),
                                            a[n(D)] = e[n(pt) + n(Z)](),
                                            Wt[n(ft)](".", t[n(ht)](0)))
                                                return Wt[n(gt)](Kt, t, a[n(mt)]);
                                            continue;
                                        case "4":
                                            if ((i = e[n(X)](/(.*?)\?(.*)/)) && (a[n(yt)] = i[2],
                                            a[n(_t)] = Wt[n(vt)]("?", i[2]),
                                            e = i[1]),
                                            a[n(bt)] && t[n(kt)](/^\?/))
                                                return Wt[n(Ct)](Jt, t, a[n(Tt)]);
                                            continue
                                        }
                                        break
                                    }
                                continue
                            }
                            break
                        }
                    }
function v(t) {
                        var e = 800
                          , n = 712
                          , o = 540
                          , i = 760
                          , a = 448
                          , c = 486
                          , u = 352
                          , l = 448
                          , d = 283
                          , h = 805
                          , g = 608
                          , m = 310
                          , y = 191,
                            e=undefined
                          , _ = ke(t,e)
                          , b = {
                            comoU: function(t, e, n) {
                                return t(e, n)
                            },
                            qkJPM: function(t, e, n) {
                                return t(e, n)
                            },
                            ybAQP: function(t, e) {
                                return t(e)
                            },
                            JrGSx: 'https://api.weixin.qq.com/',
                            nMcMe: function(t, e) {
                                return t(e)
                            }
                        }
                        // var _(o)='comoU',_(a)='qkJPM',_(n)='ybAQP',_(r)='JrGSx',_(s)='nMcMe',_(m)='nMcMe',_(u)='nMcMe'

                           // k = b[_(o)](f(t,e), "{}", t[_(i)])
                           k=b[_(o,e)](f(t,e),"{}",'https://miniapp.qmai.cn/web/cmk-center/marketing/canvas/advert-reach')
                          , C = {};
                        return b[_(a,e)](be, C, k[_(c,e)]),
                        b[_(u,e)](Ie, C),
                        b[_(l,e)](v, t, C),
                        t[_(i,e)][_(d,e) + "th"](b[_(h,e)]) || (xe.P(t),
                        p[_(g,e)] && b[_(m,e)](he, t)),
                        s[_(y,e)](t)
}
function Ie(t) {
                    var e = 881
                      , n = 395
                      , o = 777
                      , i = 441
                      , a = 885
                      , s = 309
                      , c = ke(t,e)
                        ,p={'needCollect':true}
                      , u = {};
                    u['xRcCf'] = function(t, e) {
                        return t < e
                    }
                    ;
                    var l = u;
                    p['needCollect'] && l[c(o)](0, Se[c(i)]) && (t[c(a) + c(s)] = Se)
                }
const Te = Ce;
var Se = "";
function we() {
                    var t, e, n = 927, o = 489, i = 489, a = 183, c = 927, u = 234, l = 195, d = 528, f = r;
                    Te[s[f(n)]] && ((e = [s[f(n)]])[f(o)](p.c),
                    e[f(o)](p.D),
                    e[f(i)](p[f(a) + "on"]),
                    t = Te[s[f(c)]](),
                    e = e[f(u)](t),
                    Se = {
                        TejFU: function(t, e) {
                            return t(e)
                        }
                    }[f(l)](ie, e[f(d)]("^")))
                }
var t={acw_tc: "ac11000117606930568474739e7bbc9983688d5babe98e8e1ca02f0618c45f"};
console.log(we())

